### ISSUE TITLE
change dummy text to valid text

### ISSUE THREAD

**Issue by varad177** [CSI-DMCE-2024/Doctor-UI-Hacktoberfest-2024#3]
![image](https://github.com/user-attachments/assets/befc0612-628b-4905-8a59-9fe913841ccd)

**some text is the dummy text in website, change them to the valid text**

**Comment by Charul00** [comment]
can i work on this @varad177

**Comment by TickleFuse09** [comment]
Let me work on this. I've been told i'm good with words

**Comment by varad177** [comment]
> Hey leads, let me work on this. I've been told i'm good with words

@TickleFuse09  work on it , complete it asap
